### ISSUE TITLE
Shows "too many VRoid bones found for `^Hips`" when Generate Humanized VRM Rig

### ISSUE THREAD

**Issue by kikouousya** [nanoskript/vrm-rigify#10]
Model: Free Mode herel https://booth.pm/ja/items/3521047
Error Message :
```
Python: Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\vrm_rigify\meta.py", line 49, in position_meta_rig
    conversions = create_bone_mapping(base_bones, vroid_rig)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\vrm_rigify\base.py", line 106, in create_bone_mapping
    assert len(vroid_matches) == 1, f"too many VRoid bones found for `{vroid_pattern}`"
AssertionError: too many VRoid bones found for `^Hips`
```
Perhaps It matched a collider here.
![image](https://github.com/nanoskript/vrm-rigify/assets/31646365/11666388-cece-4949-b439-f2064a9bd811)

And if it's possible, it's really easy to show an UI panel in blender insteading of let user perform an action. (and also could allows adding more customized options)
There is just a random tutorial I found to do that.
https://www.youtube.com/watch?v=Qyy_6N3JV3k&pp=ygUUYmxlbmRlciBwbHVnaW4gcGFuZWw%3D

**Comment by nanoskript** [comment]
Hello! Apologies for the late reply. The error in generating the model has now been fixed in: https://github.com/nanoskript/vrm-rigify/releases/tag/v0.2.0. The original model doesn't seem to have any vertex groups for the eyes, so these will need to be defined manually in order to be able to move the eyes using Rigify's eye widget.

A UI panel for generating the rig is somewhere on the roadmap. Thank you! Feel free to reopen this issue if needed.
